apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: webapp
    tier: back
spec:
  selector:
    app: webapp
    tier: back
  ports:
  - port: 5000
    targetPort: 5000
    name: http
