apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: webapp
    tier: back
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: webapp
      tier: back
  template:
    metadata:
      labels:
        app: webapp
        tier: back
    spec:
      containers:
      - name: backend
        image: {{ include "webapp.backendImage" . }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: webapp-config
        env:
        {{- if .Values.postgres.enabled }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_DB
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASS)@postgres-0.postgres-svc:5432/$(DB_NAME)"
        {{- end }}
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
